import { defineEnvVars } from '@sveltejs/kit/env';

const optional = (value: string | undefined) => (value ? value : undefined);

export const variables = defineEnvVars({
	AUTH_PASSWORD_HASH: {
		schema: optional,
		description: 'scrypt hash of the dashboard password. Generate with `npm run set-password`.'
	},
	SESSION_SECRET: {
		schema: (value) => {
			if (!value) return undefined;
			if (value.length < 32) throw new Error('SESSION_SECRET must be at least 32 characters');
			return value;
		},
		description: 'Secret used to sign session cookies. Generated by `npm run set-password`.'
	},
	HA_URL: {
		schema: (value) => (value ? value.replace(/\/+$/, '') : undefined),
		description: 'Home Assistant base URL, e.g. http://homeassistant.local:8123. Leave empty to use mock devices.'
	},
	HA_TOKEN: {
		schema: optional,
		description: 'Home Assistant long-lived access token.'
	}
});
