import { defineEnvVars } from '@sveltejs/kit/env';

const optional = (value: string | undefined) => (value ? value : undefined);

export const variables = defineEnvVars({
	AUTH_PASSWORD_HASH: {
		schema: optional,
		description: 'scrypt hash of the dashboard password. Generate with `npm run set-password`.'
	},
	SESSION_SECRET: {
		schema: (value) => {
			if (!value) return undefined;
			if (value.length < 32) throw new Error('SESSION_SECRET must be at least 32 characters');
			return value;
		},
		description: 'Secret used to sign session cookies. Generated by `npm run set-password`.'
	},
	HA_URL: {
		schema: (value) => (value ? value.replace(/\/+$/, '') : undefined),
		description: 'Home Assistant base URL, e.g. http://homeassistant.local:8123. Leave empty to use mock devices.'
	},
	HA_TOKEN: {
		schema: optional,
		description: 'Home Assistant long-lived access token.'
	},
	TOTP_SECRET: {
		schema: (value) => {
			if (!value) return undefined;
			if (!/^[A-Z2-7]{16,}=*$/i.test(value)) throw new Error('TOTP_SECRET must be base32');
			return value;
		},
		description:
			'Shared secret for 6-digit login codes (Google Authenticator). Generate with `npm run setup-2fa`. Leave empty for password-only login.'
	},
	SPOTIFY_CLIENT_ID: {
		schema: optional,
		description: 'Spotify app client ID (developer.spotify.com/dashboard). Enables the now-playing panel.'
	},
	SPOTIFY_CLIENT_SECRET: {
		schema: optional,
		description: 'Spotify app client secret.'
	},
	SPOTIFY_REFRESH_TOKEN: {
		schema: optional,
		description: 'Long-lived Spotify token for your account. Generated by `npm run setup-spotify`.'
	},
	GITHUB_TOKEN: {
		schema: optional,
		description:
			'Optional GitHub token (no scopes needed) to raise the API limit from 60 to 5,000 requests/hour.'
	}
});
